# Generated by Django 5.2 on 2025-04-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='genre',
            field=models.CharField(choices=[('MOR', 'MORAL'), ('FAN', 'Fantasy'), ('SCI', 'Sci-Fi'), ('HOR', 'Horror'), ('ROM', 'Romance'), ('MYS', 'Mystery'), ('HIS', 'Historical')], max_length=3),
        ),
    ]
